/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ApplyCategoryRouteImport } from './routes/apply.$category'
import { Route as LoanIndexRouteImport } from './routes/loan.index'
import { Route as LoanHelpRouteImport } from './routes/loan.help'
import { Route as LoanIncomeRouteImport } from './routes/loan.income'
import { Route as LoanReviewRouteImport } from './routes/loan.review'
import { Route as LoanSubmittedRouteImport } from './routes/loan.submitted'
import { Route as OfferingsIdRouteImport } from './routes/offerings.$id'
import { Route as TransferIndexRouteImport } from './routes/transfer.index'
import { Route as TransferReviewRouteImport } from './routes/transfer.review'
import { Route as TransferSuccessRouteImport } from './routes/transfer.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyCategoryRoute = ApplyCategoryRouteImport.update({
  id: '/apply/$category',
  path: '/apply/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanIndexRoute = LoanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoanRoute,
} as any)
const LoanHelpRoute = LoanHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => LoanRoute,
} as any)
const LoanIncomeRoute = LoanIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => LoanRoute,
} as any)
const LoanReviewRoute = LoanReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LoanRoute,
} as any)
const LoanSubmittedRoute = LoanSubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => LoanRoute,
} as any)
const OfferingsIdRoute = OfferingsIdRouteImport.update({
  id: '/offerings/$id',
  path: '/offerings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferIndexRoute = TransferIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransferRoute,
} as any)
const TransferReviewRoute = TransferReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => TransferRoute,
} as any)
const TransferSuccessRoute = TransferSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => TransferRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/loan': typeof LoanRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRouteWithChildren
  '/apply/$category': typeof ApplyCategoryRoute
  '/loan/help': typeof LoanHelpRoute
  '/loan/income': typeof LoanIncomeRoute
  '/loan/review': typeof LoanReviewRoute
  '/loan/submitted': typeof LoanSubmittedRoute
  '/offerings/$id': typeof OfferingsIdRoute
  '/transfer/review': typeof TransferReviewRoute
  '/transfer/success': typeof TransferSuccessRoute
  '/loan/': typeof LoanIndexRoute
  '/transfer/': typeof TransferIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apply/$category': typeof ApplyCategoryRoute
  '/loan/help': typeof LoanHelpRoute
  '/loan/income': typeof LoanIncomeRoute
  '/loan/review': typeof LoanReviewRoute
  '/loan/submitted': typeof LoanSubmittedRoute
  '/offerings/$id': typeof OfferingsIdRoute
  '/transfer/review': typeof TransferReviewRoute
  '/transfer/success': typeof TransferSuccessRoute
  '/loan': typeof LoanIndexRoute
  '/transfer': typeof TransferIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/loan': typeof LoanRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRouteWithChildren
  '/apply/$category': typeof ApplyCategoryRoute
  '/loan/help': typeof LoanHelpRoute
  '/loan/income': typeof LoanIncomeRoute
  '/loan/review': typeof LoanReviewRoute
  '/loan/submitted': typeof LoanSubmittedRoute
  '/offerings/$id': typeof OfferingsIdRoute
  '/transfer/review': typeof TransferReviewRoute
  '/transfer/success': typeof TransferSuccessRoute
  '/loan/': typeof LoanIndexRoute
  '/transfer/': typeof TransferIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/loan'
    | '/login'
    | '/signup'
    | '/transfer'
    | '/apply/$category'
    | '/loan/help'
    | '/loan/income'
    | '/loan/review'
    | '/loan/submitted'
    | '/offerings/$id'
    | '/transfer/review'
    | '/transfer/success'
    | '/loan/'
    | '/transfer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/apply/$category'
    | '/loan/help'
    | '/loan/income'
    | '/loan/review'
    | '/loan/submitted'
    | '/offerings/$id'
    | '/transfer/review'
    | '/transfer/success'
    | '/loan'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/loan'
    | '/login'
    | '/signup'
    | '/transfer'
    | '/apply/$category'
    | '/loan/help'
    | '/loan/income'
    | '/loan/review'
    | '/loan/submitted'
    | '/offerings/$id'
    | '/transfer/review'
    | '/transfer/success'
    | '/loan/'
    | '/transfer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoanRoute: typeof LoanRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TransferRoute: typeof TransferRouteWithChildren
  ApplyCategoryRoute: typeof ApplyCategoryRoute
  OfferingsIdRoute: typeof OfferingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$category': {
      id: '/apply/$category'
      path: '/apply/$category'
      fullPath: '/apply/$category'
      preLoaderRoute: typeof ApplyCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan/': {
      id: '/loan/'
      path: '/'
      fullPath: '/loan/'
      preLoaderRoute: typeof LoanIndexRouteImport
      parentRoute: typeof LoanRoute
    }
    '/loan/help': {
      id: '/loan/help'
      path: '/help'
      fullPath: '/loan/help'
      preLoaderRoute: typeof LoanHelpRouteImport
      parentRoute: typeof LoanRoute
    }
    '/loan/income': {
      id: '/loan/income'
      path: '/income'
      fullPath: '/loan/income'
      preLoaderRoute: typeof LoanIncomeRouteImport
      parentRoute: typeof LoanRoute
    }
    '/loan/review': {
      id: '/loan/review'
      path: '/review'
      fullPath: '/loan/review'
      preLoaderRoute: typeof LoanReviewRouteImport
      parentRoute: typeof LoanRoute
    }
    '/loan/submitted': {
      id: '/loan/submitted'
      path: '/submitted'
      fullPath: '/loan/submitted'
      preLoaderRoute: typeof LoanSubmittedRouteImport
      parentRoute: typeof LoanRoute
    }
    '/offerings/$id': {
      id: '/offerings/$id'
      path: '/offerings/$id'
      fullPath: '/offerings/$id'
      preLoaderRoute: typeof OfferingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer/': {
      id: '/transfer/'
      path: '/'
      fullPath: '/transfer/'
      preLoaderRoute: typeof TransferIndexRouteImport
      parentRoute: typeof TransferRoute
    }
    '/transfer/review': {
      id: '/transfer/review'
      path: '/review'
      fullPath: '/transfer/review'
      preLoaderRoute: typeof TransferReviewRouteImport
      parentRoute: typeof TransferRoute
    }
    '/transfer/success': {
      id: '/transfer/success'
      path: '/success'
      fullPath: '/transfer/success'
      preLoaderRoute: typeof TransferSuccessRouteImport
      parentRoute: typeof TransferRoute
    }
  }
}

interface LoanRouteChildren {
  LoanHelpRoute: typeof LoanHelpRoute
  LoanIncomeRoute: typeof LoanIncomeRoute
  LoanReviewRoute: typeof LoanReviewRoute
  LoanSubmittedRoute: typeof LoanSubmittedRoute
  LoanIndexRoute: typeof LoanIndexRoute
}

const LoanRouteChildren: LoanRouteChildren = {
  LoanHelpRoute: LoanHelpRoute,
  LoanIncomeRoute: LoanIncomeRoute,
  LoanReviewRoute: LoanReviewRoute,
  LoanSubmittedRoute: LoanSubmittedRoute,
  LoanIndexRoute: LoanIndexRoute,
}

const LoanRouteWithChildren = LoanRoute._addFileChildren(LoanRouteChildren)

interface TransferRouteChildren {
  TransferReviewRoute: typeof TransferReviewRoute
  TransferSuccessRoute: typeof TransferSuccessRoute
  TransferIndexRoute: typeof TransferIndexRoute
}

const TransferRouteChildren: TransferRouteChildren = {
  TransferReviewRoute: TransferReviewRoute,
  TransferSuccessRoute: TransferSuccessRoute,
  TransferIndexRoute: TransferIndexRoute,
}

const TransferRouteWithChildren = TransferRoute._addFileChildren(
  TransferRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoanRoute: LoanRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TransferRoute: TransferRouteWithChildren,
  ApplyCategoryRoute: ApplyCategoryRoute,
  OfferingsIdRoute: OfferingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
