/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StockTickerRouteImport } from './routes/stock.$ticker'
import { Route as TradeTickerRouteImport } from './routes/trade.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTickerRoute = StockTickerRouteImport.update({
  id: '/stock/$ticker',
  path: '/stock/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTickerRoute = TradeTickerRouteImport.update({
  id: '/trade/$ticker',
  path: '/trade/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deposit': typeof DepositRoute
  '/explore': typeof ExploreRoute
  '/portfolio': typeof PortfolioRoute
  '/support': typeof SupportRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/trade/$ticker': typeof TradeTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deposit': typeof DepositRoute
  '/explore': typeof ExploreRoute
  '/portfolio': typeof PortfolioRoute
  '/support': typeof SupportRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/trade/$ticker': typeof TradeTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deposit': typeof DepositRoute
  '/explore': typeof ExploreRoute
  '/portfolio': typeof PortfolioRoute
  '/support': typeof SupportRoute
  '/stock/$ticker': typeof StockTickerRoute
  '/trade/$ticker': typeof TradeTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deposit'
    | '/explore'
    | '/portfolio'
    | '/support'
    | '/stock/$ticker'
    | '/trade/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deposit'
    | '/explore'
    | '/portfolio'
    | '/support'
    | '/stock/$ticker'
    | '/trade/$ticker'
  id:
    | '__root__'
    | '/'
    | '/deposit'
    | '/explore'
    | '/portfolio'
    | '/support'
    | '/stock/$ticker'
    | '/trade/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DepositRoute: typeof DepositRoute
  ExploreRoute: typeof ExploreRoute
  PortfolioRoute: typeof PortfolioRoute
  SupportRoute: typeof SupportRoute
  StockTickerRoute: typeof StockTickerRoute
  TradeTickerRoute: typeof TradeTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$ticker': {
      id: '/stock/$ticker'
      path: '/stock/$ticker'
      fullPath: '/stock/$ticker'
      preLoaderRoute: typeof StockTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$ticker': {
      id: '/trade/$ticker'
      path: '/trade/$ticker'
      fullPath: '/trade/$ticker'
      preLoaderRoute: typeof TradeTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DepositRoute: DepositRoute,
  ExploreRoute: ExploreRoute,
  PortfolioRoute: PortfolioRoute,
  SupportRoute: SupportRoute,
  StockTickerRoute: StockTickerRoute,
  TradeTickerRoute: TradeTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
